.PHONY: clean All

All:
	@echo "----------Building project:[ replaceString - Debug ]----------"
	@cd "replaceString" && "$(MAKE)" -f  "replaceString.mk"
clean:
	@echo "----------Cleaning project:[ replaceString - Debug ]----------"
	@cd "replaceString" && "$(MAKE)" -f  "replaceString.mk" clean
