.PHONY: clean All

All:
	@echo "----------Building project:[ replaceString3 - Debug ]----------"
	@cd "replaceString3" && "$(MAKE)" -f  "replaceString3.mk"
clean:
	@echo "----------Cleaning project:[ replaceString3 - Debug ]----------"
	@cd "replaceString3" && "$(MAKE)" -f  "replaceString3.mk" clean
