.PHONY: clean All

All:
	@echo "----------Building project:[ insertString - Debug ]----------"
	@cd "insertString" && "$(MAKE)" -f  "insertString.mk"
clean:
	@echo "----------Cleaning project:[ insertString - Debug ]----------"
	@cd "insertString" && "$(MAKE)" -f  "insertString.mk" clean
